version: "3"
services:
  www:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./webroot:/srv/users/apps/
      - ./nginx/default.env_template:/etc/nginx/conf.d/default.env_template
    depends_on:
      - webapp
    environment:
      - NGINX_HOST=${DOCKER_NGINX_HOST}
      - DOLLAR=$$
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.env_template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  webapp:
    image: bitnami/php-fpm:latest
    expose:
      - 9000
    volumes:
      - ./webroot:/srv/users/apps/
      - ./php_conf/php_env.conf:/opt/bitnami/php/etc/environment.conf
    environment:
      - PHP_MEMORY_LIMIT=200M
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - APP_NAME=${APP_NAME}
      - APP_ENV=${APP_ENV}
      - APP_KEY=${APP_KEY}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=${APP_URL}
      - LOG_CHANNEL=${LOG_CHANNEL}
      - BROADCAST_DRIVER=${BROADCAST_DRIVER}
      - CACHE_DRIVER=${CACHE_DRIVER}
      - QUEUE_CONNECTION=${QUEUE_CONNECTION}
      - SESSION_DRIVER=${SESSION_DRIVER}
      - SESSION_LIFETIME=${SESSION_LIFETIME}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - MAIL_DRIVER=${MAIL_DRIVER}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USERNAME=${MAIL_USERNAME}
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - MAIL_ENCRYPTION=${MAIL_ENCRYPTION}
      
  database:
    image: mysql:latest
    command: ['--default-authentication-plugin=mysql_native_password']
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DOCKER_DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DOCKER_DB_ROOT_PASS}
      - MYSQL_USER=${DOCKER_DB_USER}
      - MYSQL_PASSWORD=${DOCKER_DB_PASS}
    
